### ISSUE TITLE
Test model code

### ISSUE THREAD

**Issue by tahirjhan** [Harry-KIT/Image-Classification-on-small-datasets-in-Pytorch#2]
Hi, Thanks for sharing your code. The code is well-written and easy to follow. However,  I did not find the test code. How do you test your final model after training? Thanks.

**Comment by aidevveloper** [comment]
Hi @tahirjhan. Thank you for your interest. I solved your problem. Please check test.py file

**Comment by Harry-KIT** [comment]
Thank you for your interest in this repo!Please give a star to this repo and share it with others!


Sent from Yahoo Mail for iPhone


On Monday, June 19, 2023, 2:42 PM, Tahir Mahmood ***@***.***> wrote:




Closed #2 as completed.
